/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionAsientosAutob;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.plaf.basic.BasicComboBoxUI;
import javax.swing.table.DefaultTableModel;
import modelo.ClaseAutobus;
import modelo.Corrida;
import modelo.ModeloTablaCorridas;
import modelo.Poblacion;

/**
 *
 * @author eskape
 */
public class ReservaBoletosAutob extends javax.swing.JFrame {
private ModeloTablaCorridas modeloTC;
    private DefaultTableModel modeloT;
    private ArrayList<Corrida> corridass;
    private Corrida corrida;
    private ArrayList<Integer> asientosOcupados;
    private Poblacion poblaciones[]={
        new Poblacion(1, "Oaxaca", "Oax"), new Poblacion(2, "Jalapa", "Ver"),new Poblacion(2, "CDMX", ""),
        new Poblacion(4, "Puebla", "Pue"), new Poblacion(5, "Nochixtlan", "Oax"), new Poblacion(6, "Cuernavaca", "Mor"),
        new Poblacion(7, "Tehuacan", "Pueb")
    };
    private ClaseAutobus claseAutobus[]={
        new ClaseAutobus(1, "Mini", 24),
        new ClaseAutobus(2, "Primera", 40),
        new ClaseAutobus(3, "Lujo", 36)
    };
    private String cOrigen ="";
    private String cDestino="";
    private int numCorSel;
    private String numCols[]= {"Num.Corr","Origen","Destino","Fecha","Hora","Clase Autobus","Precio","Lugares"};
    
    /**
     * Creates new form NewJFrame
     */
    public ReservaBoletosAutob() {
        initComponents();
    }
        public ReservaBoletosAutob(java.awt.Frame parent, boolean modal) {
        //super(parent,modal);
        initComponents();
        corridass = new ArrayList<Corrida>();
        asientosOcupados = new ArrayList<Integer>();
        formaCorridas();
        modeloTC = new ModeloTablaCorridas(corridass, numCols);
        tCorridas.setModel(modeloTC);
        tCorridas.setSelectionMode(0);//Solo se puede seleccionar un renglon
        origenDestino.setCiudades(ciudades());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        origenDestino = new Componente_OD.OrigenDestino();
        todasLasCorridas = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tCorridas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        todasLasCorridas.setText("jCheckBox1");

        tCorridas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tCorridas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(origenDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(todasLasCorridas)
                .addGap(203, 203, 203))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(origenDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(todasLasCorridas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    
        private String[] ciudades(){
        String ciuds[] = new String[poblaciones.length];
        for (int i = 0; i < ciuds.length; i++) 
            ciuds[i]= poblaciones[i].getPoblacion();
        return ciuds;
    }
    private void formaCorridas() {
        Date fecha;
        Calendar calen = Calendar.getInstance();  
        fecha = calen.getTime();
        for (int i = 0; i < 50; i++) {
            calen.set(Calendar.DAY_OF_MONTH, i+1);
            calen.set(Calendar.HOUR, i);
            corrida = new Corrida(i, poblaciones[i%7], poblaciones[i%3+4], fecha, claseAutobus[i%3], 100+i*50);
            corridass.add(corrida);
        }
    }
    private boolean comparaDMA(Date fechaa,Date fechab){
        DateFormat formatoAMD = new SimpleDateFormat("yyyyMMdd");
        String sfechaa;
        String sfechab;
        sfechaa = formatoAMD.format(fechaa);
        sfechab = formatoAMD.format(fechab);
            
        return sfechaa.equals(sfechab);
    }
    private void seleccionCorrida(String cO,String cD,Date fes){
        ArrayList<Corrida> corriSel = new ArrayList<Corrida>();
        if(todasLasCorridas.isSelected())
            corriSel = corridass;
        else
            for (int i = 0; i < corridass.size(); i++) {
                if (corridass.get(i).getOrigen().equalsIgnoreCase(cO) &&
                    corridass.get(i).getDestino().equalsIgnoreCase(cD)&&
                    comparaDMA(corridass.get(i).getFecha(), fes)) {
                    
                    corriSel.add(corridass.get(i));
                }
                modeloTC = new ModeloTablaCorridas(corriSel, numCols);
                tCorridas.setModel(modeloT);
            }
    }
    private JComboBox crearComboTipo(){
        JComboBox combo = new JComboBox(new String[]{"Adulto","Tercera Edad","Niño"}){
            public void updateUI(){
                super.updateUI();
                setBorder(BorderFactory.createEmptyBorder());
                setUI(new BasicComboBoxUI(){
                    @Override 
                        protected JButton createArrowButton(){
                        JButton button = super.createArrowButton();
                        button.setContentAreaFilled(false);
                        button.setBorder(BorderFactory.createEmptyBorder());
                        return button;
                    }
            });
            }
            
        };
        return combo;
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservaBoletosAutob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservaBoletosAutob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservaBoletosAutob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservaBoletosAutob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservaBoletosAutob().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private Componente_OD.OrigenDestino origenDestino;
    private javax.swing.JTable tCorridas;
    private javax.swing.JCheckBox todasLasCorridas;
    // End of variables declaration//GEN-END:variables
}
